server:
  port: 8080
  tomcat:
    max-connections: 10000
    max-threads: 500

# mybatis 基本配置
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.suixingpay.pojo
  configuration:
    map-underscore-to-camel-case: true
#
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
spring:
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB

  profiles:
    active: dev

  # MySQL 配置
  datasource:
    platform: mysql
    url: jdbc:mysql://172.16.41.67:3306/seckill_zwl?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: team3member
    password: team3team3
    driver-class-name: com.mysql.jdbc.Driver

  # Redis 配置
  redis:
    host: 172.16.41.92
    port: 6379
    pool:
      maxWait: 1500
      maxActive: 2048
      minIdle: 20
      maxIdle: 200

# 全局异常配置
suixingpay:
  exception:
    enabled: true #是否启用全局异常处理器
    char-set: UTF-8 #字符集
    #error-page-url: /errorpage # 错误页面路径, 如果是前后端分离系统，不需要配置此项，如果配置此项，非ajax请求的异常都会跳转到此页面
    #send-error-type: forward # 前后端分离忽略此项，页面跳转方式 forward或redirect
    #code-name: errorCode # 前后端分离忽略此项，通过forward或redirect 到 error-page-url（错误页面）时，错误码的参数名称
    error-message-name: errorMessage # 前后端分离忽略此项，通过forward或redirect 到 error-page-url（错误页面）时，错误信息参数名称
    show-error-field-name: true #是否显示验证失败的字段名称
    return-unkown-exception-message: true #是否返回未知异常信息，例如网络连接超时等。
    unkown-exception-message: "未知错误" #自定义未知异常信息，如果不自定义，默认为null，会获取Exception中的Message
    overriddenErrorController: true # 是否覆盖默认的ErrorController，默认值为true
    escapeIllegalChars: false # 防止XSS去除异常信息中的特殊字符(<和>)，默认值为false(3.0.6版本增加)
